context:
  name: loguru-cpp
  # The upstream repo is not very active anymore and contain commits since the last release
  # from 09/2019. A proper git tag has been asked at https://github.com/emilk/loguru/issues/253.
  # In the meantime, we use the last version with the commit hash and date as the version string.
  git_hash_date: "20260731"
  git_hash: f9a628b67bf960bbeb6eddd1227a3e6f4d631f1c
  version: ${{ "2.1.0.post" + git_hash_date }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # See https://github.com/emilk/loguru/issues/253
  url: https://github.com/emilk/loguru/archive/${{ git_hash }}.tar.gz
  sha256: 11965f3417b9f70a5e42c6cd6ab5d9e0b63a812a38b9a3ec42b5b5a52a14fae2

build:
  number: 0
  script:
    - if: win
      then: |
        cmake -GNinja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
            -DBUILD_SHARED_LIBS=ON ^
            -DLOGURU_WITH_STREAMS=ON ^
            -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ^
            %SRC_DIR%
        ninja install
      else: |
        cmake -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=$PREFIX \
              -DBUILD_SHARED_LIBS=ON \
              -DLOGURU_WITH_STREAMS=ON \
              -DCMAKE_CXX_FLAGS="-Wno-type-limits" \
              $SRC_DIR
        ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x.x') }}

tests:
  - package_contents:
      include:
        - loguru/loguru.hpp
      lib:
        - loguru
      files:
        - "*/loguru.pc"
        - "*/loguru-config-version.cmake"
        - "*/loguru-config.cmake"
        - "*/loguru-targets.cmake"

about:
  summary: A lightweight C++ logging library
  license: Unlicense
  license_file: LICENSE
  homepage: https://github.com/emilk/loguru

extra:
  recipe-maintainers:
    - mgorny
